probes:
  enabled: true

kobocat:
  image:
    # -- KoboCat docker image name
    name: kobotoolbox/kobocat
    # -- KoboCat docker image tag
    # see https://hub.docker.com/r/kobotoolbox/kobocat for latest tags
    tag: "2.021.24b"
  # -- DNS subdomain name to serve the form server from
  subdomain: kc
  # -- Dictionary of env variables to pass
  extraEnv: {}
  memory:
    requested: 2.0Gi
    limit: 3.0Gi

kpi:
  image:
    # -- kpi docker image name
    # See https://hub.docker.com/r/kobotoolbox/kpi for list of tags
    name: kobotoolbox/kpi
    # -- kpi docker image tag
    tag: "2.021.41"
  # -- DNS subdomain to serve the main UI from
  subdomain: kobo
  # -- Dictionary of env variables to pass
  extraEnv:
    DJANGO_LANGUAGE_CODES: en fr es ar zh-hans hi ku
    KOBO_SUPPORT_URL: http://support.kobotoolbox.org/
  memory:
    requested: 2.0Gi
    limit: 3.0Gi

uwsgi:
  workers: "4"
  cheaper: "2"
  cheaperRssLimitSoft: "1073741824"

enketo:
  image:
    # -- Enketo image name - the web-based form preview and filling UI
    name: enketo/enketo-express
    # -- Enketo image tag
    # See https://hub.docker.com/r/kobotoolbox/enketo-express-extra-widgets
    tag: "3.0.4"
  # -- DNS subdomain to serve Enketo from
  subdomain: ee
  # -- Number of Enketo pods
  replicas: 1
  # -- Random API key
  apiKey: WEHQJCXHJ2XOBXGOGMXCUJYXQP9ZZFVY4FHLCSKJIWAWPTCMGMECGNBCHXVBFCFT1H5TQTQCKB0J7DF2X23WC7EHOCCVQ7K8CY6QO9C8NMERACUM6S2QQEER
  # -- Random API key
  encryptionKey: w0RkyuQSB33md8cZB5Xx
  # -- Random API key
  lessSecureEncryptionKey: wUNQWPwA3bDVzckKKtS4
  # -- Enketo configuration - will be evaluated as a template
  # @default -- see `values.yaml`
  config: |-
    {
      "app name": "Enketo Express for KoBo Toolbox",
      "linked form and data server": {
        "name": "KoBo Toolbox",
        "server url": "",
        "api key": "{{ .Values.enketo.apiKey }}"
      },
      "encryption key": "{{ .Values.enketo.encryptionKey }}",
      "less secure encryption key": "{{ .Values.enketo.lessSecureEncryptionKey }}",
      "widgets": [
        "note",
        "select-desktop",
        "select-mobile",
        "autocomplete",
        "geo",
        "textarea",
        "url",
        "table",
        "radio",
        "date",
        "time",
        "datetime",
        "select-media",
        "file",
        "draw",
        "rank",
        "likert",
        "range",
        "columns",
        "image-view",
        "comment",
        "image-map",
        "date-native",
        "date-native-ios",
        "date-mobile",
        "text-max",
        "text-print",
        "rating",
        "thousands-sep"
      ],
      "redis": {
        "cache": {
          "host": "{{ .Release.Name }}-rediscache-master",
          {{- if .Values.rediscache.usePassword }}
          "password": "{{ .Values.global.redis.password }}",
          {{- end }}
          "port": "6379"
        },
        "main": {
          "host": "{{ .Release.Name }}-redismain-master",
          {{- if .Values.redismain.usePassword }}
          "password": "{{ .Values.global.redis.password }}",
          {{- end }}
          "port": "6379"
        }
      },
      "google": {
        "api key": "{{ .Values.external.google.apiKey }}",
        "analytics": {
          "ua": "{{ .Values.external.google.analyticsToken }}",
          "domain": "{{ .Values.general.externalScheme }}://{{ .Values.enketo.subdomain }}.{{ .Values.general.externalDomain }}{{ .Values.general.publicPort }}"
        }
      },
      "payload limit": "1mb",
      "text field character limit": 1000000,
      "maps": [
        {
          "name": "humanitarian",
          "tiles": [ "https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png" ],
          "attribution": "&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap</a> & <a href=\"https://www.hotosm.org/updates/2013-09-29_a_new_window_on_openstreetmap_data\">Yohan Boniface & Humanitarian OpenStreetMap Team</a> | <a href=\"https://www.openstreetmap.org/copyright\">Terms</a>"
        },
        {
          "name": "satellite",
          "tiles": [ "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" ],
          "attribution": "Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community"
        },
        {
          "name": "terrain",
          "tiles": [ "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png" ],
          "attribution": "&copy; <a href=\"https://openstreetmap.org\">OpenStreetMap</a> | <a href=\"https://www.openstreetmap.org/copyright\">Terms</a>"
        },
        {
          "name": "streets",
          "tiles": [ "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" ],
          "attribution": "&copy; <a href=\"https://openstreetmap.org\">OpenStreetMap</a> | <a href=\"https://www.openstreetmap.org/copyright\">Terms</a>"
        }
      ]
    }

nginx:
  config: |-
    charset     utf-8;
    gzip on;
    gzip_disable "msie6";

    # TODO: explore if we can use paths instead of subdomains...?

    # Default configuration
    server {
      listen 80 default_server;
      listen [::]:80 default_server;

      root /var/www/html;

      # Add index.php to the list if you are using PHP
      index index.html index.htm index.nginx-debian.html;

      server_name $hostname;

      location / {
        # return empty response
        return 204;
      }

      # Proxy ELB status
      location ~ /elb/([^/]*)/(.*)$ {
        resolver 127.0.0.1;
        proxy_pass http://127.0.0.1/$2;
        proxy_set_header Host $1;
        proxy_intercept_errors on;
        access_log  off;
      }
    }

    # KoBoCAT HTTP.
    server {
      listen      80;
      server_name {{ .Values.kobocat.subdomain }}.{{ include "internal_domain" . }} {{ .Values.kobocat.subdomain }}.docker.internal {{ .Values.kobocat.subdomain }}.{{ .Values.general.externalDomain }};

      # Allow 100M upload
      client_max_body_size 100M;
      # Support bigger headers. Useful for huge cookies
      large_client_header_buffers 8 16k;

      location / {
        uwsgi_read_timeout 130;
        uwsgi_send_timeout 130;
        uwsgi_pass localhost:8001;
        # For setting HTTP headers, see http://stackoverflow.com/a/14133533/1877326.
        uwsgi_param HTTP_X_REAL_IP $remote_addr;
        uwsgi_param HTTP_X_FORWARDED_FOR $remote_addr;
        # uwsgi_param HTTP_X_FORWARDED_PROTO $scheme;
        include /etc/nginx/uwsgi_params;

        # Support longer query strings. See issue #147
        uwsgi_buffers 8 16k;
        uwsgi_buffer_size 16k;
      }

      location /static {
        alias /srv/www/kobocat;
      }

      # media files
      location /protected/ {
        internal;
        alias /media/;
      }
    }

    # KoBoForm HTTP.
    server {
      listen      80;
      server_name {{ .Values.kpi.subdomain }}.{{ include "internal_domain" . }} {{ .Values.kpi.subdomain }}.docker.internal {{ .Values.kpi.subdomain }}.{{ .Values.general.externalDomain }};

      # Allow 100M upload
      client_max_body_size 100M;
      # Support bigger headers. Useful for huge cookies
      large_client_header_buffers 8 16k;

      location ~ ^/forms/(.*) {
        return 301 /$1;
      }

      location /static {
        alias /srv/www/kpi;

        # gzip configs from here
        # http://stackoverflow.com/a/12644530/3088435
        gzip on;
        gzip_disable "msie6";
        gzip_comp_level 6;
        gzip_min_length 1100;
        gzip_buffers 16 8k;
        gzip_proxied any;
        gzip_types
          text/plain
          text/css
          text/js
          text/xml
          text/javascript
          application/javascript
          application/x-javascript
          application/json
          application/xml
          application/xml+rss;
      }

      # public media, e.g. custom logos (KPI `ConfigurationFile`s)
      location /media/__public {
          alias /srv/kpi_media/__public;
      }

      error_page 418 = /static/html/Offline.html;

      location / {
        uwsgi_read_timeout 130;
        uwsgi_send_timeout 130;
        uwsgi_pass localhost:8003;
        # For setting HTTP headers, see http://stackoverflow.com/a/14133533/1877326.
        uwsgi_param HTTP_X_REAL_IP $remote_addr;
        uwsgi_param HTTP_X_FORWARDED_FOR $remote_addr;
        # uwsgi_param HTTP_X_FORWARDED_PROTO $scheme;
        include /etc/nginx/uwsgi_params;

        # Support longer query strings. See issue #147
        uwsgi_buffers 8 16k;
        uwsgi_buffer_size 16k;
      }

      # media files
      location /protected/ {
        internal;
        alias /media/;
      }

    }

general:
  # -- Replica for the kpi+kobocat pod. __WARNING__: if using more than 1 replicas, you NEED to use a ReadWriteMany accessmode in mediaStorage.accessMode, and a storage class that supports it!
  replicas: 1
  # -- Parent domain to serve all apps from
  # __WARNING__: The subdomains MUST be reachable since the application will try to call itself at this address
  externalDomain: example.com
  # -- Public URL scheme
  externalScheme: http
  # -- Public URL port
  externalPort:
  # -- Random Django secret
  djangoSecret: EKMvRtT2RFB3xDvFty4SVCsTyaQAHS9aA2mkRqtTp9zQYz48fp
  # -- Enable various debug flags?
  debug: false
  superUser:
    # -- Admin user name - This user will have access to kobotoolbox UI but also the built-in Django admin interface (/admin)
    username: kobo
    # -- Admin user password
    password: kobo
  # -- Support email visible from the website
  supportEmail: support@example.com
  # -- Service type to expose
  serviceType: ClusterIP
  # -- Set this to true in order to force internal resolution of external domains, in case those aren't reachable from inside the containers.
  # Useful for troubleshooting, but won't work if the public scheme is https
  forceInternal: false
  mediaStorage:
    # -- Storage size for uploaded media volume
    size: 10Gi
    # -- Storage class will default to global.storageClass if provided, but can be specifically overridden here
    storageClass: ""
    # -- Needs to be ReadWriteMany if you intend to scale to more than 1 pod!
    accessMode: ReadWriteOnce

ingress:
  # -- Install ingress?
  enabled: false
  # -- Ingress annotations
  annotations:
    {}
    # You typically want to enable large media uploads
    # nginx.ingress.kubernetes.io/proxy-body-size: 100M
  # -- Ingress TLS settings
  tls: {}

external:
  google:
    apiKey: ""
    analyticsToken: ""
  ravenDSN:
    kobocat: ""
    kpi: ""
    kpiJs: ""

smtp:
  # -- SMTP Host
  host: smtp.gmail.com
  # -- Use TLS for SMTP?
  tls: true
  # -- SMTP port
  port: "587"
  # -- SMTP Username
  user: ""
  # -- SMTP Password
  password: ""
  # -- SMTP "from" address
  from: ""

global:
  redis:
    # -- Redis password
    password: brFdS9b7Xp
  # -- Will be used by this and all subcharts
  storageClass: standard

rediscache:
  enabled: true
  usePassword: true
  cluster:
    # disable slaves
    enabled: false
    slaveCount: 1

redismain:
  enabled: true
  usePassword: true
  cluster:
    # disable slaves
    enabled: false
    slaveCount: 1

# -- Standard MongoDB values
# See https://artifacthub.io/packages/helm/bitnami/mongodb for doc
# @default -- see `values.yaml`
mongodb:
  # -- Install MongoDB?
  enabled: true
  # TODO: support external db
  # For now we only support a db installed with a subchart

  auth:
    rootPassword: kobo
    username: kobo
    password: kobo
    database: formhub
  initdbScripts:
    index.js: |
      db.getSiblingDB('{{ .Values.auth.database }}').instances.createIndex( { _userform_id: 1 } )
    create-user.js: |
      db.createUser({
        user: "{{ .Values.auth.username }}",
        pwd: "{{ .Values.auth.password }}",
        roles: [ { role: 'readWrite', db: "{{ .Values.auth.database }}" } ]
      })

# -- Standard postgres chart values
# See https://artifacthub.io/packages/helm/bitnami/postgresql for docs
# @default -- see `values.yaml`
postgresql:
  # -- Install Postgres?
  enabled: true
  # -- DB name for the form server
  kobocatDatabase: kobocat
  # -- DN name for the main Kobo UI
  kpiDatabase: koboform

  # TODO: support external db
  # For now we only support a db installed with a subchart
  initdbScriptsConfigMap: "{{ .Release.Name }}-postgres-init-scripts"
  initdbUser: postgres
  initdbPassword:  ${postgresqlPostgresPassword}

  postgresqlPostgresPassword: admin
  postgresqlUsername: postgres
  postgresqlPassword: kobo
